<!DOCTYPE unspecified PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<form name="login" 
	  action="<?php echo $this->url(array('controller'=>'index','action'=>'add01'));?>" 
	  method="post">
	姓名：<input type="text" name="user_name" id="user_name"	/><br />
	密码：<input type="text" name="user_pwd" id="user_pwd" />
	<input type="submit" value="提交" />
</form>

