<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<link href="head.html" />

</head>

<body>
 	
    <div id="footerbig">
        <!--footer start -->
          <div id="footer">
            <ul>
              <li><a href="#">首页</a></li>
                    <li>|</li>
                    <li><a href="#">酒店信息</a></li>
                    <li>|</li>
                    <li><a href="#">航空公司信息</a></li>
                    <li>|</li>
                    <li><a href="#">航班信息</a></li>
                    <li>|</li>
                    <li><a href="#">会员管理</a></li>
                    <li>|</li>
                    <li><a href="#">客服服务</a></li>
                    <li>|</li>
                    <li><a href="#">帮助</a></li>
                    <li>|</li>
                    <li><a href="#">关于</a></li>
            </ul>
                 <p>Copyrioht © Eco Mania 2007 All Rights Reserved</p>
				 <p>Powered by <a href="http://templatekingdom.com" target="_blank">TemplateKingdom.com</a></p>
          </div>
        <!--footer end -->
    </div>
    <!--100% footer end -->

</body>
</html>
