<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>航空订票系统</title>
<link href="css/style.css" rel="stylesheet" type="text/css" />

</head>

<body>
	<!--header start -->
    	<div id="header">
        	
            <h1>
            	<span>Look Towords A New Future</span>
</h1>
            <ul class="navi">
           	  <li><a href="#" class="hover">首页</a></li>
                <li><a href="#">酒店信息</a></li>
                <li><a href="#">航空公司信息</a></li>
                <li><a href="#">航班查询</a></li>
                <li><a href="#">会员管理</a></li>
                <li><a href="#">客服服务</a></li>
                <li><a href="#">帮助</a></li>
      <li class="noborder"><a href="about.html" target="_blank">关于</a></li>
          </ul>
            <form name="serach" method="post" action="#">
            	<label>Search</label>
                <input type="text" name="serch" value="" class="textbox" />
                <input type="submit" name="sib" class="go" value="" />
            </form>
            
            <ul class="login">
            	<li><a href="#" class="sub">Subscribe</a></li>
                <li><a href="#" class="loginHer"></a></li>
            </ul>
</div>
</body>
</html>